# Numpy
- C언어로 구현된 파이썬 라이브러리
- 고성능 수치계산을 위해 제작
- Numerical Python
- 벡터 및 행렬 연산에 매우 편리한 기능 제공
- Pandas와 matplotlib과 더블어 데이터분석에 필수 라이브러리
- 기본적으로 array 단위로 데이터 처리
- 대표적인 자료형 : ndarray 객체

## Numpy

In [1]:
# numpy 모듈 불러오기
import numpy as np

## Array 정의 및 사용

In [2]:
# Python의 List 이용
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [3]:
b = [1, 2, 3, 4, 5]
b

[1, 2, 3, 4, 5]

In [4]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [6]:
# array 형태(크기) 확인
arr1.shape

(5,)

In [7]:
# array 자료형 확인
arr1.dtype

dtype('int32')

## 1.3 배열 생성 : Numpy가 제공하는 함수를 이용한 단순 배열 생성
- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linespace, logspace

In [8]:
# 0인 배열 생성 : zeros(배열의 크기)
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [9]:
b = np.zeros(5, dtype="i")
b

array([0, 0, 0, 0, 0], dtype=int32)

- numpy 자료형, dtype의 접두사
- "i" : 정수형
- "u" : uint(unsign int), 부호가 없는 정수
- "f" : float
- "b" : 논리형(bool)
- "c" : 복소수(complex)
- "s" : 문자열(string)

In [10]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [11]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
c = np.zeros((5, 2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [13]:
e = np.ones((2, 3, 4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
# 기존의 배열의 크기를 그대로 사용하여 배열 생성
## zeros_like
## ones_like
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
f = np.ones_like(b)
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
g = np.empty((4, 3))
g

array([[1.46695114e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 2.14321575e-312, 3.69776220e-062],
       [5.27390942e-091, 2.74954875e+180, 8.40869129e+164],
       [1.90352982e+185, 3.99910963e+252, 9.13597212e+169]])

In [17]:
# range() : 순차리스트, 수열생성 함수
# range(5) : 0, 1, 2, 3, 4
# range(1, 10) : 1, 9
# arange() : Numpy 버전의 range 명령어이다.
np.arange(10) # 0 ~ n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [20]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치행렬
- 행과 열을 바꾸는 기능
- T

In [21]:
A = np.array([[1, 2, 3],[4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형
- 배열의 크기 속성 : shape, 배열명.속성
- 배열의 크기 변경 : reshape

In [24]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a.shape

(12,)

In [26]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [30]:
# 다차원 배열을 1차원 배열로 생성하는 flatten, ravel 메서드
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [35]:
x.shape

(5,)

In [36]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [37]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
# 차원만 증가시키는 newaxis
x

array([0, 1, 2, 3, 4])

In [39]:
x.shape

(5,)

In [40]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])