<a href="https://colab.research.google.com/github/codedyasai/Python_Intermediate/blob/main/01_Numpy_%EC%8B%9C%EC%9E%91_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- c언어로 구현된 파이썬 라이브러리
- 고성능 수치계산을 위해 제작
- Numerical Python
- 벡터 및 행렬 연산에 매우 편리한 기능 제공
- Pandas와 matplotlib과 더불어 데이터분석에 필수 라이브러리
- 기본적으로 array 단위로 데이터 처리
- 대표적인 자료형 : ndarray 객체

In [ ]:
# numpy 모듈 불러오기
import numpy as np

## Array 정의 및 사용

In [ ]:
# Python의 List 이용
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
b = [1,2,3,4,5]
b

[1, 2, 3, 4, 5]

In [ ]:
arr1 = np.array(a)
a


[1, 2, 3, 4, 5]

In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [ ]:
# array 형태(크기) 확인
arr1.shape

(5,)

In [ ]:
# array의 자료형 확인
arr1.dtype

dtype('int64')

## 1.3 배열 생성 : Numpy가 제공하는 함수를 이용한 단순 배열 생성
- zeros. ones
- zeros_like, ones_like
- empty
- linespace, log

In [ ]:
# 0인 배열 생성: zeros(배열의 크기)
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
b = np.zeros(5, dtype='i')
b


array([0, 0, 0, 0, 0], dtype=int32)

- numpy 자료형, dtype의 접두사
- 'i': 정수형
- 'u': unit(unsign int), 부호가 없는 정수
- 'f': float
- 'b': 논리형(bool)
- 'c': 복소수(complex)
- 's': 문자열(string)

In [ ]:
x = np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [ ]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.zeros((5,2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [ ]:
e = np.ones((2,3,4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# 기존의 배열의 크기를 그대로 사용하여 배열 생성
## zeros_like
## ones_like
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
f = np.ones_like(b)
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
g = np.empty((4,3))
g

array([[4.66140064e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
# range(): 순차리스트, 수열생성 함수
# range(5): 0,1,2,3,4
# range(1, 10): 1,9
# arange(): numpy 버전의 range 명령어이다.

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치행렬
- 행과 열을 바꾸는 기능
- T

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형
- 배열의 크기 속성 : shape, 배열명.속성
- 배열의 크기 변경: reshape

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape

(12,)

In [ ]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
# 다차원 배열을 1차원 배열로 생성하는 flatten, revel 메서드
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x.shape

(5,)

In [ ]:
x.reshape(1,5) # 대괄호가 하나 더생겼다. 위의 x랑 다르다

array([[0, 1, 2, 3, 4]])

In [ ]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# 차원만 증가시키는 newaxis 명령어
x

array([0, 1, 2, 3, 4])

In [ ]:
x[:, np.newaxis] # 2차원이 됨

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 2 Numpy 배열의 연산


In [ ]:
x = np.arange(1, 10001)
y =np.arange(10001, 20001)

In [ ]:
%%time
res = np.zeros_like(x)
for i in range(10000):
    res[i] = x[i] + y[i]

CPU times: user 2.71 ms, sys: 0 ns, total: 2.71 ms
Wall time: 2.7 ms


In [ ]:
res[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [ ]:
%%time
z = y + x

CPU times: user 71 µs, sys: 9 µs, total: 80 µs
Wall time: 85.6 µs


In [ ]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])


In [ ]:
a == b

array([False,  True, False,  True])

In [ ]:
a >= b

array([False,  True,  True,  True])

In [ ]:
np.all(a == b)

False

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
10**a

array([    1,    10,   100,  1000, 10000])

In [ ]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅(broadcasting)
- 서로 크기가 다른 배열의 사칙연산을 수행하는 기능
- 크기가 작은 배열이 자동적으로 크기가 큰 배열의 크기로 맞춰지는 기능

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
y = np.ones_like(x)

In [ ]:
x + y

array([1, 2, 3, 4, 5])

In [ ]:
x + 1

array([1, 2, 3, 4, 5])

In [ ]:
y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
y + 1 # 이게 브로드캐스팅이다

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
z = np.ones_like(y)
z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
y + z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 그룹함수 or 차원 축소 연산
- 최대/최소: min, max, argmin, argmax
- 기초통계: sum, mean, median, std, var
- 논리연산: all, any

In [ ]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [ ]:
np.sum(x)

10

In [ ]:
x.sum()

10

In [ ]:
x = np.array([1,3,2])
x

array([1, 3, 2])

In [ ]:
np.min(x)

1

In [ ]:
x.min()

1

In [ ]:
x.argmin()

0

In [ ]:
x.argmax()

1

In [ ]:
x.mean()

2.0

In [ ]:
np.mean(x)

2.0

In [ ]:
np.median(x)

2.0

In [ ]:
y = np.array([1,2,3,1])

In [ ]:
np.median(y)

1.5

In [ ]:
np.all([True, True, False])

False

In [ ]:
np.any([True,True,False])

True

In [ ]:
a = np.zeros((100, 100), dtype='i')
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [ ]:
np.any(a!=0)

False

In [ ]:
np.all(a==a)

True

In [ ]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,4])
c = np.array([6,4,4,5])

In [ ]:
((a <= b) & (b <= c)).all()

True

- 축(axis): axis=0(열), axis=1(행), default(axis=0)

In [ ]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum()

6

In [ ]:
x.sum(axis=0)

array([3, 3])

In [ ]:
x.sum(axis=1)

array([2, 4])

## 정렬(sort)
- 2차원 이상일 경우에는 행이나 열을 각각 따로 정렬한다.
- axis = 0이면 각 열을 기준으로 정렬, axis = 1이면 각 행을 기준으로 정렬
- 생략하면 axis = 0
- axis = -1

In [ ]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]
              ])

In [ ]:
np.sort(a) # axis = 1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
np.sort(a, axis = 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [ ]:
np.sort(a, axis = -1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
# 정렬을 하지 않고 순서만 알고 싶다면 argsort 명령을 사용한다.
a = np.array([4,2,3,5])
b = np.argsort(a)

In [ ]:
a[b]

array([2, 3, 4, 5])

In [ ]:
np.sort(a)

array([2, 3, 4, 5])

## Fancy Indexing: 팬시 인덱싱
- boolean 인덱싱을 이용하는 것
- 마스크 인덱싱
- 규칙이 일정하지 않지만 원하는 데이터를 추출하고자 할 때 사용한다.

In [ ]:
names = np.array(['park','park','kim','john',
                  'lee', 'park', 'hong', 'park'])
names

array(['park', 'park', 'kim', 'john', 'lee', 'park', 'hong', 'park'],
      dtype='<U4')

In [ ]:
names.shape

(8,)

In [ ]:
# 정규분포 : np.random.randn(), 평균 = 0, 표준편차 = 1
# np.random.randn() : 0~1 사이의 난수 발생
data = np.random.randn(8,4)
data

array([[ 0.71657238, -0.49779596, -0.68635465, -0.70645295],
       [-1.04677668,  0.52067459,  0.68433164, -0.02706099],
       [ 0.29626796,  1.64184117,  0.39526923,  0.45907652],
       [ 0.82858097,  0.20155023,  0.53605869,  2.31415048],
       [-0.65619269,  2.9931197 ,  1.12268052,  0.10662136],
       [-0.3739188 , -0.10769267,  2.15192646,  0.07506156],
       [-0.67023024,  0.93812079, -0.47177809, -1.50059016],
       [-2.78714613,  2.99661408,  1.50131825, -0.13349239]])

In [ ]:
data.shape

(8, 4)

In [ ]:
index = (names == 'park')
data[index, :]

array([[ 0.71657238, -0.49779596, -0.68635465, -0.70645295],
       [-1.04677668,  0.52067459,  0.68433164, -0.02706099],
       [-0.3739188 , -0.10769267,  2.15192646,  0.07506156],
       [-2.78714613,  2.99661408,  1.50131825, -0.13349239]])

In [ ]:
# 요소가 'kim'인 행의 데이터만 추출
data[names == 'kim', :]

array([[0.29626796, 1.64184117, 0.39526923, 0.45907652]])

In [ ]:
data[2, :]

array([0.29626796, 1.64184117, 0.39526923, 0.45907652])

In [ ]:
# kim과 hong
data[(names == 'kim')| (names =='hong'), :]

array([[ 0.29626796,  1.64184117,  0.39526923,  0.45907652],
       [-0.67023024,  0.93812079, -0.47177809, -1.50059016]])

In [ ]:
data

array([[ 0.71657238, -0.49779596, -0.68635465, -0.70645295],
       [-1.04677668,  0.52067459,  0.68433164, -0.02706099],
       [ 0.29626796,  1.64184117,  0.39526923,  0.45907652],
       [ 0.82858097,  0.20155023,  0.53605869,  2.31415048],
       [-0.65619269,  2.9931197 ,  1.12268052,  0.10662136],
       [-0.3739188 , -0.10769267,  2.15192646,  0.07506156],
       [-0.67023024,  0.93812079, -0.47177809, -1.50059016],
       [-2.78714613,  2.99661408,  1.50131825, -0.13349239]])

In [ ]:
# 0번째 열의 값이 0보다 작은 행의 추출
data[:,0] < 0

array([False,  True, False, False,  True,  True,  True,  True])

In [ ]:
data[data[:, 0] < 0 , :]

array([[-1.04677668,  0.52067459,  0.68433164, -0.02706099],
       [-0.65619269,  2.9931197 ,  1.12268052,  0.10662136],
       [-0.3739188 , -0.10769267,  2.15192646,  0.07506156],
       [-0.67023024,  0.93812079, -0.47177809, -1.50059016],
       [-2.78714613,  2.99661408,  1.50131825, -0.13349239]])

In [ ]:
# 0번째 열의 값이 0보다 작은 행의 2, 3번째 열의 값만 추출
data[data[:,0] < 0, 2:4]


array([[ 0.68433164, -0.02706099],
       [ 1.12268052,  0.10662136],
       [ 2.15192646,  0.07506156],
       [-0.47177809, -1.50059016],
       [ 1.50131825, -0.13349239]])

In [ ]:
# 0번째 열의 값이 0보다 작은 행의 2, 3번째 열의 값을 0으로 치환
data[data[:,0] < 0, 2:4] = 0
data

array([[ 0.25222057,  1.11713483, -1.09346652,  0.09707589],
       [ 1.20165107,  1.47194366,  0.14269049,  0.36862084],
       [-1.11749199, -1.13695042,  0.        ,  0.        ],
       [-0.14943011, -0.92079508,  0.        ,  0.        ],
       [-1.25988776,  1.07946361,  0.        ,  0.        ],
       [-1.88583699, -0.52474485,  0.        ,  0.        ],
       [ 0.01341185, -0.3377571 ,  0.35299192, -1.49039829],
       [ 1.13946393, -1.71754845, -1.19088986,  0.4195491 ]])

# 3 기술통계분석

In [ ]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 3.1 데이터의 개수: len

In [ ]:
len(x)

26

## 3.2 평균: mean

In [ ]:
np.mean(x)

4.8076923076923075

## 3.3 분산: var

In [ ]:
np.var(x)

115.23224852071006

In [ ]:
# 비편향 분산
np.var(x, ddof=1)

119.84153846153846

## 3.4 표준편차 : std

In [ ]:
np.std(x)

10.734628476137871

## 3.5 최대값과 최소값: max, min

In [ ]:
np.max(x)

23

In [ ]:
np.min(x)

-24

## 3.6 중앙값 : median

In [ ]:
np.median(x)

5.0

## 3.7 사분위수 : quantile, percentile

In [ ]:
np.percentile(x, 0) # 최소값

-24.0

In [ ]:
np.percentile(x, 25) # 1사분위수

0.0

# 4 난수(random number)

## 4.1 시드설정(seed): 0과 같거나 큰 정수

In [ ]:
np.random.seed(0)

In [ ]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(5) # 위랑 다르게 나옴

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [ ]:
np.random.seed(0)

In [ ]:
np.random.rand(5) # 시드값 주고 발생한 145행이랑 값이 같음

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [ ]:
arr1 = np.random.random((3,3)) # 0~1 사이의 실수 균등분포
arr2 = np.random.normal(2, 1, (3,2)) # 평균(2), 편차(1) 정규분포
arr3 = np.random.randn(2,3) # 표준 정규분포, 평균(0), 편차(1)
arr4 = np.random.randint(0,10, (2,2)) # 정수로

In [ ]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[[0.31542835 0.36371077 0.57019677]
 [0.43860151 0.98837384 0.10204481]
 [0.20887676 0.16130952 0.65310833]]
[[1.77406034 0.34542923]
 [1.36027736 1.5205802 ]
 [2.3113635  1.22397953]]
[[-0.30736481 -0.36652394  1.11971196]
 [-0.45792242  0.4253934  -0.02797118]]
[[7 5]
 [9 0]]


## 4.2 데이터 샘플링(sampling), shuffle 명령과 같다
- np.choice(배열, size, replace, p)
- 배열: arange(n)

In [ ]:
np.random.choice(5, 5, replace=False)

array([0, 1, 4, 3, 2])

In [ ]:
np.random.choice(5,3, replace=False)

array([4, 0, 1])

In [ ]:
np.random.choice(5,10)

array([3, 3, 3, 2, 3, 4, 1, 2, 3, 1])

In [ ]:
np.random.choice(5,10, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 0, 2, 0, 3, 3, 3, 2, 2, 3])

In [ ]:
# 0에서 1 사이의 균일분포
np.random.rand(10)

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [ ]:
np.random.rand(3,5)

array([[0.63892108, 0.89155444, 0.68005557, 0.44919774, 0.97857093],
       [0.11620191, 0.7670237 , 0.41182014, 0.67543908, 0.24979628],
       [0.31321833, 0.96541622, 0.58846509, 0.65966841, 0.53320625]])

In [ ]:
# np.random.randint(low, high=None, size)
np.random.randint(10, size = 10) # 0~10 사이의 숫자 10개를 뽑으라는 뜻

array([3, 1, 8, 0, 4, 9, 6, 5, 7, 8])

In [ ]:
np.random.randint(10, 20, size = 10)

array([18, 19, 12, 18, 16, 16, 19, 11, 16, 18])

In [ ]:
np.random.randint(10, 20, size = (3,5))

array([[18, 13, 12, 13, 16],
       [13, 16, 15, 17, 10],
       [18, 14, 16, 15, 18]])

## 4.3 정수 데이터 카운팅
- unique: 중복을 제거하고 중복되지 않은 값

In [ ]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [ ]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
a

array(['a', 'b', 'b', 'c', 'a'], dtype='<U1')

In [ ]:
np.unique(a)

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
index, count = np.unique(a,return_counts=True)

In [ ]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
count

array([2, 2, 1])

# Data Analysis - 2nd

In [ ]:
# zeros, ones, full(size, k), eye

a = np.full((2,3), 5)
print(a)

# eye: 정방행렬(행과 열의 수가 같은거)
b = np.eye(3)
print(b)

[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[2][0]

7

In [ ]:
arr2d[2,0]

7

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = a

In [ ]:
b = a # b = a[:]
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0,0] = 100
print(a)
print(b)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
# copy()
c = a.copy()
print(c)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
c[0,0] = 1
print(c)
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr # 2x3x3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1 = arr[0].copy() # 깊은 복사
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[0][1]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[0,1, :]

array([4, 5, 6])

In [ ]:
arr = np.arange(15).reshape((3, -1))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
ary1 = np.array([1,2,2,3,4,4,5,6,7,8,8,8])
np.random.shuffle(ary1)

In [ ]:
ary1

array([1, 8, 2, 7, 5, 4, 8, 4, 6, 8, 3, 2])