<a href="https://colab.research.google.com/github/codedyasai/Python_Intermediate/blob/main/01_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%EC%8B%9C%EC%9E%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. *시작하기*

In [ ]:
print('Hello World')

Hello World


# 2. Numpy(넘파이)
  - Numerical Python의 줄임말
  - Numpy는 벡터 및 행렬 연산에 편리한 기능을 제공
  - Pandas와 더불어 데이터 분석에 대표적인 라이브러리
  - 넘파이 배열이라고 부름, 대표적인 자료형 Ndarray
  - python 자료구조: 변수, list, tuple, set, dict
  - R 자료구조: matrix(2차원 배열), array(n차원 배열), dataframe
  


In [ ]:
# 모듈 연결
import numpy as np

- 파이썬의 List 자료형을 확장한 개념으로 처리속도가 빠르다.
- 배열: 적은 메모리로 많은 데이터를 빠르게 처리한다.
- 모든 원소가 같은 자료형이어야 한다.
- 다차원 배열 자료구조 ndarray 클래스 제공

In [ ]:
# 리스트 객체 생성
a = [1,2,3]
b = [4,5,6]

print('a: ', a)
print('b: ', b)

a:  [1, 2, 3]
b:  [4, 5, 6]


In [ ]:
c = [1,2,3, 'a', 'b', 'c', [5,6,7]]
print(c)

[1, 2, 3, 'a', 'b', 'c', [5, 6, 7]]


In [ ]:
# 리스트 연산 : '+', '*' 밖에 되지가 않는다. 위에 보이는 것처럼 안에 넣는 자료형이 너무 자유롭기 때문
print(a+b)

[1, 2, 3, 4, 5, 6]


In [ ]:
print(a*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


# 3. 1차원 배열 만들기
  - python의 List를 이용한 ndarray 객체 생성
  - np.array() 함수를 이용한 배열 생성

In [ ]:
data1 = [1,2,3,4,5]
print(data1)
print(type(data1))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 3-1. 벡터화 연산(Vectorized operation)
- 스칼라: 1개의 값을 가진 자료형
- 벡터: 1개 이상의 값을 가진 자료형
- 자료구조의 요소단위로 계산을 수행하는 것을 벡터화연산이라고 부른다.

In [ ]:
print(a+b)

[1, 2, 3, 4, 5, 6]


In [ ]:
res = []
for i in range(3):
    temp = a[i] + b[i]
    res.append(temp)

print(res)

[5, 7, 9]


In [ ]:
arr2 = np.array(a)
arr3 = np.array(b)
print(arr2 + arr3)

[5 7 9]


In [ ]:
x = [1,2,3,4,5]
print(x*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
res = [x[i]*2 for i in range(5)]
print(res)

[2, 4, 6, 8, 10]


In [ ]:
data = np.array(x)
print(data*2)

[ 2  4  6  8 10]


In [ ]:
# type(): 자료형
print(type(data))

<class 'numpy.ndarray'>


In [ ]:
# dtype = data type, 요소의 자료형
print(data.dtype)

int64


### numpy자료형
- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 unit(8, 16, 32, 64)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 논리형 bool(True, False)
- 문자형 string

In [ ]:
# shape : 배열의 형태(크기), 1차원, 2차원, 3차원...
print(data.shape)

(5,)


## 3-2. 2차원 배열 만들기
- 행과 열을 가진 배열
- 2차원 배열 행렬(matrix): row, column

In [ ]:
y= [[1,2,3], [4,5,6]]
print(y)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
arr4 = np.array(y)
print(arr4)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 행의 갯수
len(arr4)

2

In [ ]:
# 열의 갯수
len(arr4[0])

3

In [ ]:
data2 = np.array([[1,2,3],[4,5,6]])
data2

array([[1, 2, 3],
       [4, 5, 6]])

## 3-3. 3차원 배열 만들기

In [ ]:
d = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[11,12,13,14],[15,16,17,18], [19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

## 3-4 배열의 차원과 크기
- ndim 속성: 배열의 차원
- shape 속성: 배열의 크기

In [ ]:
a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b.shape)


2
(2, 3)


In [ ]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


# 4. 배열의 인덱싱(Indexing)
- 리스트의 인덱싱과 동일하다

In [ ]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


In [ ]:
b = np.array([[0,1,2], [3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print(b[0,0])
print(b[0,1])
print(b[-1,-1])

0
1
5


## 5. 배열 슬라이싱(slicing): [행 시작:행 마지막], [: , :]
- 파이썬의 슬라이싱과 동일하다


In [ ]:
c = np.array([[0,1,2,3],[4,5,6,7]])
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# 첫번째 행 전체
c[0, : ]

array([0, 1, 2, 3])

In [ ]:
# 두번째 열 전체
c[:, 1]

array([1, 5])

In [ ]:
# 두번째 행의 두번열부터 마지막열까지
c[1, 1:]

array([5, 6, 7])

In [ ]:
c[:2, :2]

array([[0, 1],
       [4, 5]])